{
 "title": "RED: сервис api",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Rate: запросов в секунду",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(http_requests_total{job=\"api\"}[1m]))\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Errors: доля ошибок",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_errors_total{job=\"api\"}[1m])) / sum(rate(http_requests_total{job=\"api\"}[1m]))\r\n",
     "legendFormat": "доля ошибок"
    }
   ]
  },
  {
   "title": "Duration: p95 времени ответа",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, path) (rate(http_request_duration_seconds_bucket{job=\"api\"}[1m])))\r\n",
     "legendFormat": "{{path}}"
    }
   ]
  }
 ]
}