apiVersion: v1
kind: Service
metadata:
  name: jaeger-ui-nodeport
  labels:
    app: jaeger-ui
spec:
  type: NodePort
  selector:
    {{- toYaml .Values.selector | nindent 4 }}
  ports:
    - name: query
      port: {{ .Values.uiPort }}
      targetPort: {{ .Values.uiPort }}
      nodePort: {{ .Values.nodePort }}
