{
 "title": "Контейнер api: ресурсы и лимиты",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "OOM-события",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (name) (container_oom_events_total{name=\"api-mon\"})\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU, ядер",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_cpu_usage_seconds_total{name=\"api-mon\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Троттлинг, суммарно с/с",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_cpu_cfs_throttled_seconds_total{name=\"api-mon\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Память: доля от лимита",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (name) (container_memory_working_set_bytes{name=\"api-mon\"})\r\n  / max by (name) (container_spec_memory_limit_bytes{name=\"api-mon\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Троттлинг: доля периодов",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by (name) (rate(container_cpu_cfs_throttled_periods_total{name=\"api-mon\"}[1m]))\r\n  / max by (name) (rate(container_cpu_cfs_periods_total{name=\"api-mon\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}